services:
    # Core ORM services
    orm.driver:
        class: Bravo3\Orm\Drivers\Redis\RedisDriver
    orm.mapper: "@orm.mapper.chained"
    orm.mapper.chained:
        class: Bravo3\Orm\Mappers\Chained\ChainedMapper
    orm.mapper.annotation:
        class: Bravo3\Orm\Mappers\Annotation\AnnotationMapper
        tags: [{ name: orm.mapper }]
    orm.em:
        class: Bravo3\Orm\Services\EntityManager
        arguments: ["@orm.driver", "@orm.mapper", %kernel.cache_dir%]
    # User & security management
    orm.user_provider:
        class: Bravo3\OrmBundle\Services\OrmUserProvider
        arguments: ["@orm.em", "@security.encoder_factory"]
    orm.security_manager:
        class: Bravo3\OrmBundle\Services\OrmSecurityManager
        arguments: ["@orm.user_provider", "@security.encoder_factory", "@event_dispatcher", "@security.token_storage"]
    orm.session_handler:
        class: Bravo3\OrmBundle\Session\OrmSessionHandler
        arguments: ["@orm.em"]
    # Portation services
    orm.entity_locator:
        class: Bravo3\Orm\Services\EntityLocator
        arguments: ["@orm.em"]
    orm.map_writer.yaml:
        class: Bravo3\Orm\Mappers\Yaml\YamlMapWriter
        arguments: ["@=service('kernel').getRootDir() ~ '/config/entity_map.yml'"]
        calls:
            - [setInputManager, ["@orm.em"]]

parameters:
    entity_locations:
        - ['src/Bravo3/OrmBundle/Entity', 'Bravo3\OrmBundle\Entity']
