services:
    orm.driver:
        class: Bravo3\Orm\Drivers\Redis\RedisDriver
    orm.mapper: @orm.mapper.chained
    orm.mapper.chained:
        class: Bravo3\Orm\Mappers\Chained\ChainedMapper
    orm.mapper.annotation:
        class: Bravo3\Orm\Mappers\Annotation\AnnotationMapper
        tags: [{ name: orm.mapper }]
    orm.em:
        class: Bravo3\Orm\Services\EntityManager
        arguments: [@orm.driver, @orm.mapper, %kernel.cache_dir%]
    orm.user_provider:
        class: Bravo3\OrmBundle\Services\OrmUserProvider
        arguments: [@orm.em, @security.encoder_factory]
    orm.security_manager:
        class: Bravo3\OrmBundle\Services\OrmSecurityManager
        arguments: [@orm.user_provider, @security.encoder_factory, @event_dispatcher]
    orm.session_handler:
        class: Bravo3\OrmBundle\Session\OrmSessionHandler
        arguments: [@orm.em]
